config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :users

  resources :accas do
    collection do
      get :get_acca
      get :import
      post :import_acca
    end
  end

  resources :selections do
    collection do
    end
  end

  # namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions
    end
  # end
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  module Category
    FOOTBALL     = "Football"
    HORSE_RACING = "Horse Racing"
  end
  CATEGORIES = Category.constants.collect {|c| Category.const_get c }
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  include SelectionsHelper
  before_action :authenticate_user!

  def index
    @selections = Selection.all.order("name ASC")
  end

  def new
    @selection = Selection.new
  end

  def create

  end

  def edit
    @selection = Selection.find(params[:id])
    @selection_accas = Acca.includes(:legs).where("legs.selection = ?", @selection.id).references(:legs)
  end

  def update
    @selection = Selection.find(params[:id])
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to selections_path, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        flash.now[:alert] = @selection.errors.full_messages
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @selection = Selection.find(params[:id])
  end

  def destroy
    @selection = Selection.find(params[:id])
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_path, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def selection_params
    params.require(:selection).permit(:name, :category, :hidden)
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
  def get_acca_selections acca
    selections = acca.legs.map(&:selection)
    p "HERE123"
    p acca.legs.map{|leg| leg.selection}
    p selections
    return Selection.find(selections).map(&:name).join(", ") rescue nil
  end
end

app/views/selections/_form.html.erb
<%= form_for @selection do |f| %>
  <div class="form-group">
    <%= f.label :hidden %>
    <%= f.check_box :hidden %>
  </div>

  <%# f.submit class: "btn btn-primary" %>
<% end %>

app/views/selections/edit.html.erb
<div class="page-title">
  <div class="flex-row v-middle space-between">
    <h1><%= @selection.name %></h1>
    <div class="width-50">
      <%= render "form" %>
    </div>
  </div>
</div>

<div class="flex-row">
  <div class="width-50">
    <div class="flex-row flex-wrap" style="margin: -5px;">
      <div class="widget-container width-50">
        <div class="widget">
          <h3 class="widget-title">Win Rate</h3>
          <h2>3</h2>
        </div>
      </div>
      <div class="widget-container width-50">
        <div class="widget">
          <h3 class="widget-title">Number of bets</h3>
          <h2>3</h2>
        </div>
      </div>
      <div class="widget-container width-50">
        <div class="widget">
          <h3 class="widget-title">Total Staked</h3>
          <h2>3</h2>
        </div>
      </div>
      <div class="widget-container width-50">
        <div class="widget">
          <h3 class="widget-title">Profit/Loss</h3>
          <h2>3</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="width-50">
    <h2><%= @selection.name %> Accas</h2>
    <% @selection_accas.each do |acca| %>
      <%= get_acca_selections(acca) %>
    <% end %>
  </div>
</div>

app/views/selections/index.html.erb
<div class="page-title">
  <h1>Teams</h1>
</div>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Hidden</th>
    <th>&nbsp;</th>
  </tr>
  <% @selections.each do |selection| %>
    <tr>
      <td><%= selection.name %></td>
      <td><%= selection.category %></td>
      <td><%= selection.hidden %></td>
      <td class="text-right">
        <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_selection_path(selection) %> |
        <%= link_to "<i class='fa fa-trash-o' aria-hidden='true'></i> Delete".html_safe, selection_path(selection), method: :delete, class: "text-danger", data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/selections/new.html.erb
<div class="page-title">
  <h1>New Selection</h1>
</div>

<%= render "form" %>