config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :users

  resources :accas do
    collection do
      get :get_acca
      get :import
      post :import_acca
    end
  end

  resources :selections do
    collection do
    end
  end

  # namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions
    end
  # end
end

app/models/acca.rb
class Acca < ActiveRecord::Base
  belongs_to :user

  has_many :legs, inverse_of: :acca, dependent: :delete_all
  accepts_nested_attributes_for :legs, reject_if: :all_blank, allow_destroy: true

  module Category
    FOOTBALL     = "Football"
    # HORSE_RACING = "Horse Racing"
  end
  CATEGORIES = Category.constants.collect {|c| Category.const_get c }

  module Type
    SINGLE       = "Single"
    DOUBLE       = "Double"
    TREBLE       = "Treble"
    FOUR_FOLD    = "4 Fold"
    FIVE_FOLD    = "5 Fold"
    SIX_FOLD     = "6 Fold"
    SEVEN_FOLD   = "7 Fold"
    EIGHT_FOLD   = "8 Fold"
    NINE_FOLD    = "9 Fold"
    TEN_FOLD     = "10 Fold"
    ELEVEN_FOLD  = "11 Fold"
    TWELVE_FOLD  = "12 Fold"
    LUCKY_31     = "Lucky 31"
    LUCKY_15     = "Lucky 15"
    LUCKY_63     = "Lucky 63"
  end
  BET_TYPES = Type.constants.collect {|c| Type.const_get c }
end

app/controllers/accas_controller.rb
require 'nokogiri'

class AccasController < ApplicationController
  include AccasHelper
  before_action :authenticate_user!

  def index
    accas = current_user.accas.order("date DESC").group_by{|a| a.date}
    @accas = Kaminari.paginate_array(accas, total_count: accas.count).page(params[:page]).per(7)
  end

  def new
    @acca = Acca.new
  end

  def import

  end

  def import_acca
    html = Nokogiri::HTML(params[:acca_html])

    acca_date   = Date.parse(html.css('.bet-confirmation-header-datetime').text.downcase.strip)
    acca_type   = get_bet_type(html.css('.bet-confirmation-breakdown-link').text.downcase.gsub('bet type:', '').strip)
    acca_stake  = html.css('.bet-confirmation-info-table-value').first.text.downcase.gsub('£','').strip
    acca_return = html.css('.bet-confirmation-info-table-footer-value').text.downcase.gsub('to return £','').gsub('return £','').gsub('net return £','').strip

    Acca.create!(
      date: acca_date,
      category: Acca::Category::FOOTBALL,
      bet_type: acca_type,
      stake: acca_stake.to_f,
      return: acca_return.to_f,
      user_id: current_user.id
    )

    legs = html.css('.bet-confirmation-details-item')
    legs.each do |leg|
      selection  = get_selection(leg.css('.bet-confirmation-details-row-selectionname').text.gsub('Draw Or ','').gsub('Or Draw','').strip)
      odds       = leg.css('.bet-confirmation-details-row-odds').text.downcase.strip
      event      = leg.css('.bet-confirmation-details-row-eventname').text.gsub(/\d+/,'').gsub('/','').strip
      leg_type   = get_leg_type(leg.css('.bet-confirmation-details-row-plbtdescription').text.downcase.strip)
      leg_result = leg.css('.bet-confirmation-details-row-status').text.downcase.strip

      Leg.create!(
        acca_id:   Acca.last.id,
        leg_type:  leg_type,
        selection: selection,
        event:     event,
        won:       leg_result == 'won',
        placed:    nil,
        lost:      leg_result == 'lost',
        void:      leg_result == 'void',
        course:    nil,
        race_time: nil,
        odds: odds
      )
    end
    @acca = Acca.last
  end

  def create
    Acca.create!(date: params[:acca][:date], category: params[:acca][:category], bet_type: params[:acca][:bet_type], stake: params[:acca][:stake], return: params[:acca][:return], user_id: current_user.id)
    params[:acca][:legs_attributes].each do |k,leg|
      selection = get_selection leg[:selection]
      opponent = get_selection leg[:opponent]
      Leg.create!(
        acca_id:   Acca.last.id,
        leg_type:  leg[:leg_type],
        selection: selection,
        opponent:  opponent,
        won:       leg[:won],
        placed:    leg[:placed],
        lost:      leg[:lost],
        void:      leg[:void],
        course:    leg[:course],
        race_time: leg[:race_time]
      )
    end
    redirect_to accas_path
  end

  def get_selection selection_name
    selection = Selection.where(name: selection_name).first.id rescue nil
    unless selection.present? || selection_name.blank?
      Selection.create(name: selection_name)
      selection = Selection.last.id
    end
    return selection
  end

  def edit
    @acca = Acca.find(params[:id])
  end

  def update
    @acca = Acca.find(params[:id])
    respond_to do |format|
      if @acca.update(acca_params)
        format.html { redirect_to accas_path, notice: 'Acca was successfully updated.' }
        format.json { render :index, status: :ok, location: @acca }
      else
        flash.now[:alert] = @acca.errors.full_messages
        format.html { render :edit }
        format.json { render json: @acca.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @acca = Acca.find(params[:id])
  end

  def destroy
    @acca = Acca.find(params[:id])
    @acca.destroy
    respond_to do |format|
      format.html { redirect_to accas_path, notice: 'Acca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_acca
    @acca = Acca.find(params[:id])
  end

  private
  def acca_params
    params.require(:acca).permit(:date, :category, :bet_type, :stake, :return, legs_attributes: [:id, :leg_type, :selection, :event, :won, :placed, :lost, :void, :odds, :_destroy])
  end
end

app/helpers/accas_helper.rb
module AccasHelper
  def get_bet_type bet_type
    case bet_type
    when "doubles"
        return Acca::Type::DOUBLE
    when "trebles"
        return Acca::Type::TREBLE
    when "4 folds"
        return Acca::Type::FOUR_FOLD
    when "5 folds"
        return Acca::Type::FIVE_FOLD
      when "6 folds"
        return Acca::Type::SIX_FOLD
      when "7 folds"
        return Acca::Type::SEVEN_FOLD
      when "8 folds"
        return Acca::Type::EIGHT_FOLD
    else
      return Acca::Type::SINGLE
    end
  end

  def get_leg_type leg_type
    case leg_type
      when "full time result", "fulltime result"
        return Leg::Type::WIN
      when "draw"
        return Leg::Type::DRAW
      when "double chance"
        return Leg::Type::DOUBLE_CHANCE
      when "draw no bet"
        return Leg::Type::DRAW_NO_BET
      when "both teams to score"
        return Leg::Type::BTTS
      when "alternative total goals", "total goals"
        return Leg::Type::TOTAL_GOALS
      when "alternative corners"
        return Leg::Type::TOTAL_CORNERS
      when "result/both teams to score"
        return Leg::Type::WIN_AND_BTTS
      when "to qualify"
        return Leg::Type::TO_QUALIFY
    else
      return leg_type
    end
  end

  def get_acca_selections acca
    selections = acca.legs.map(&:selection)
    return Selection.find(selections).map(&:name).join(", ") rescue nil
  end

  def leg_class leg
    case true
    when leg.won
      return "won"
    when leg.placed
      return "placed"
    when leg.lost
      return "lost"
    when leg.void
      return "void"
    else
      return "void"
    end
  end

end

app/views/accas/_acca.html.erb
<div class="modal-header">
  <h1>
    <%= @acca.bet_type %> <small>[<%= @acca.date.strftime("%d/%m/%Y") %>]</small>
  </h1>
  <a href="#" class="close-modal" data-empty="true"></a>
</div>
<div class="modal-notice <%= @acca.return > 0 ? 'success' : 'danger' %>">
  <%= "#{@acca.return > 0 ? 'Well done!' : 'Unlucky!'}" %> Your stake of <%= number_to_currency(@acca.stake, unit: "£") %> returned <%= number_to_currency(@acca.return, unit: "£") %>
</div>

<div class="line-divide"></div>

<ul class="acca-legs no-padding-top no-padding-bottom">
  <% @acca.legs.each do |leg| %>
    <li>
      <div class="flex-row v-middle">
        <span class="leg-result <%= leg_class(leg) %>"></span>
        <h2>
          <%= Selection.find(leg.selection).name %>
          <small class="muted"><%= leg.event %> | <%= leg.leg_type.titleize %></small>
        </h2>
      </div>
      <p><%= leg.odds %></p>
    </li>
  <% end %>
</ul>

<div class="line-divide"></div>

<%= link_to "Delete This Acca", acca_path(@acca), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>

app/views/accas/_accas.html.erb
<% unless @accas.empty? %>
  <%= paginate @accas, window: 0 %>
  <% @accas.each do |date,accas| %>
    <div class="date-heading">
      <h2><%= "#{date.strftime('%A')} (#{date.strftime("%d/%m/%Y")})" %></h2>
      <div class="flex-row v-middle">
        <p class="muted"><%= "#{pluralize(accas.count, 'Bet')} | Total Staked: #{number_to_currency(accas.map{|a| a.stake rescue 0}.sum, unit: '£')} | Total Return: #{number_to_currency(accas.map{|a| a.return rescue 0}.sum, unit: '£')}" %></p>
        <span class="chev mar-left-5 <%= accas.map(&:return).sum > 0 ? 'profit' : 'loss' %>"></span>
      </div>
    </div>
    <% accas.each do |acca| %>
      <div class="acca-card small mar-bottom-5">
        <div class="acca-card-header">
          <h2>
            <small><%= acca.date %></small>
            <%= acca.bet_type %>
          </h2>
          <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_acca_path(acca) %>
        </div>
        <ul class="acca-legs small">
          <li><%= link_to get_acca_selections(acca), "", class: "open-modal get-acca", data: { acca_id: acca.id } %></li>
        </ul>
        <div class="acca-card-footer">
          <div>
            <p class="bold">Stake: <%= number_to_currency(acca.stake, unit: "£") %></p>
          </div>
          <div>
            <p class="bold">Return: <%= number_to_currency(acca.return, unit: "£") %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= paginate @accas, window: 0 %>
<% else %>
  <div class="alert alert-info">No Accas</div>
<% end %>

app/views/accas/_form.html.erb
<% @body_class = "extra-padding" %>

<%= form_for @acca do |f| %>
  <div class="acca-form-container">
    <div class="form-group-inline">
      <div class="form-group relative">
        <%= f.text_field :date, value: @acca.date || Date.today %>
      </div>
      <div class="form-group">
        <%= f.select :category, options_for_select(Acca::CATEGORIES), {}, {onchange: "checkCategory()"} %>
      </div>
      <div class="form-group multi relative">
        <%= f.select :bet_type, options_for_select(Acca::BET_TYPES), prompt: "Select Bet Type" %>
      </div>
      <div class="form-group">
        <%= f.text_field :stake, placeholder: "£ Stake", value: @acca.stake || 5 %>
      </div>
      <div class="form-group">
        <%= f.text_field :return, placeholder: "£ Return", value: @acca.return || 0 %>
      </div>
    </div>

    <div class="line-divide"></div>

    <h2>Selections</h2>

    <div class="mar-top-10" id="legs">
      <%= f.fields_for :legs do |leg| %>
        <%= render "leg_fields", f: leg %>
      <% end %>
    </div>

    <%= link_to_add_association 'Add Selection', f, :legs, class: "open-modal add-leg", 'data-association-insertion-node' => '#legs' %>

    <div class="form-actions">
      <%= f.submit "Save Acca", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

<%= render "leg_popup" %>

<script>
  $(document).on('turbolinks:load', function() {
    $("#acca_date").datetimepicker({
      defaultDate: moment(),
      format: 'YYYY-MM-DD'
    });

    // Fill in form fields after closing modal
    $("body").on("click",".save-leg",function(event) {
      event.preventDefault();
      $(".modal-overlay").fadeOut();
      form_data = $(".popup-form").serializeArray();
      $leg = $(".nested-fields").last();
      $(form_data).each(function(i,field) {
        if ($leg.find(".field_"+field["name"]).is(":checkbox")) {
          $leg.find(".field_"+field["name"]).parent().parent().find("input").prop("checked",false);
          $leg.find(".field_"+field["name"]).prop("checked",true);
        } else {
          $leg.find(".field_"+field["name"]).val(field["value"]);
        }
      });
    });

    $("body").on("click",".add-another",function(event) {
      event.preventDefault();
      // Add another leg by clicking the add leg button
      $(".add-leg").click();
      // TODO: Make this a function
      form_data = $(".popup-form").serializeArray();
      $leg = $(".nested-fields").last().prev(".nested-fields");
      $(form_data).each(function(i,field) {
        if ($leg.find(".field_"+field["name"]).is(":checkbox")) {
          $leg.find(".field_"+field["name"]).parent().parent().find("input").prop("checked",false);
          $leg.find(".field_"+field["name"]).prop("checked",true);
        } else {
          $leg.find(".field_"+field["name"]).val(field["value"]);
        }
      });
      // Clear fields
      $(".clear-field").val("");
      // Focus on selection input
      $(".selection-field").focus();
    });

    $("body").on("click",".add-leg",function(event) {
      event.preventDefault();
      // Focus on selection input
      setTimeout(function() {
        $(".selection-field").focus();
      },500);
    });

    // Multiselect setup
    $('.multi-select').multiselect({
      enableFiltering: true,
      enableCaseInsensitiveFiltering: true,
      includeSelectAllOption: true
    });
    // Open / close multiselects
    $(".multiselect").click(function(event){
      event.stopPropagation();
      $(".multiselect-container").not($(this).next(".multiselect-container")).removeClass("active");
      $(this).next(".multiselect-container").addClass("active");
      return false;
    });
    // Close all multiselects when clicking outside
    $(window).click(function() {
      $(".multiselect-container").removeClass("active");
    });

    // Results checkbox toggle
    $("body").on("click",".result-checkbox",function() {
      $(this).parent().find("input").prop("checked",false);
      $(this).find("input").prop("checked",true);
    });
  });

  // Show/hide opponent for different bet category
  function checkCategory() {
    if ($("#acca_category").val() != "Football") {
      $(".football-fields").hide();
      $(".horse-fields").show();
    } else {
      $(".horse-fields").hide();
      $(".football-fields").show();
    }
  }

  $("#legs").on("cocoon:after-insert", function(e, insertedItem) {
    var availableTags = <%= raw Selection.all.map(&:name) %>;
    $('.selections').on("focus", function(){
      $(this).autocomplete({
        minLength: 2,
        source: availableTags
      });
    });

    // After insterting a new leg check the acca category and show/hide opponent field
    checkCategory();
  });

</script>

app/views/accas/_imported_acca.html.erb
<div class="acca-card">
  <div class="acca-card-header">
    <h2>
      <small><%= @acca.date %></small>
      <%= @acca.bet_type %>
    </h2>
    <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_acca_path(@acca) %>
  </div>
  <ul class="acca-legs">
    <% @acca.legs.each do |leg| %>
      <li>
        <div class="flex-row v-middle">
          <span class="leg-result <%= leg_class(leg) %>"></span>
          <h2>
            <%= Selection.find(leg.selection).name %>
            <small class="muted"><%= leg.event %> | <%= leg.leg_type.titleize %></small>
          </h2>
        </div>
        <p><%= leg.odds %></p>
      </li>
    <% end %>
  </ul>
  <div class="acca-card-footer">
    <span>
      <h2>
        <small>Stake:</small>
        <%= number_to_currency(@acca.stake, unit: "£") %>
      </h2>
    </span>
    <span>
      <h2>
        <small>Return:</small>
        <%= number_to_currency(@acca.return, unit: "£") %>
      </h2>
    </span>
  </div>
</div>

app/views/accas/_leg_fields.html.erb
<div class="relative mar-top-5 nested-fields">
  <div class="leg-container">
    <div class="flex-row">
      <div class="form-group full no-margin">
        <%= f.select :leg_type, options_for_select(Leg::BET_TYPES), {}, {class: "field_bet_type"} %>
      </div>
    </div>

    <div class="flex-row mar-top-5 mar-bottom-5">
      <div class="form-group full no-margin ui-widget">
        <%= f.text_field :selection, class: "selections field_selection", placeholder: "Selection" %>
      </div>
    </div>

    <div class="flex-row horse-fields">
      <div class="form-group full no-margin mar-right-5">
        <%= f.select :course, options_for_select(Leg::COURSES), {}, {class: "field_course"} %>
      </div>
      <div class="form-group full no-margin mar-left-5">
        <%= f.text_field :race_time, class: "selections field_race_time", placeholder: "Race Time" %>
      </div>
    </div>

    <div class="checkbox-group mar-top-5">
      <label class="result-checkbox">
        <%= f.check_box :won, checked: true, class: "field_won" %>
        <span><i class="fa fa-smile-o" aria-hidden="true"></i> Won</span>
      </label>
      <label class="result-checkbox">
        <%= f.check_box :placed, class: "field_placed" %>
        <span><i class="fa fa-meh-o" aria-hidden="true"></i> Placed</span>
      </label>
      <label class="result-checkbox">
        <%= f.check_box :lost, class: "field_lost" %>
        <span><i class="fa fa-frown-o" aria-hidden="true"></i> Lost</span>
      </label>
      <label class="result-checkbox">
        <%= f.check_box :void, class: "field_void" %>
        <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Void</span>
      </label>
    </div>
    <%= link_to_remove_association "Remove Selection", f, class: "remove-leg" %>
  </div>
</div>

app/views/accas/_leg_popup.html.erb
<div class="modal-overlay" style="display:none;">
  <div class="modal">
    <div class="modal-body">
      <div id="modal_data">
        <div class="modal-header">
          <h1>Add Leg</h1>
          <a href="#" class="close-modal"></a>
        </div>
        <form class="popup-form">
          <div class="form-group full">
            <select name="bet_type">
              <% Leg::BET_TYPES.each do |bet_type| %>
                <option value="<%= bet_type %>"><%= bet_type %></option>
              <% end %>
            </select>
          </div>
          <div class="form-group full ui-widget">
            <input name="selection" class="selections clear-field selection-field" placeholder="Selection" />
          </div>
          <div class="form-group full horse-fields">
            <select name="course">
              <% Leg::COURSES.sort.each do |course| %>
                <option value="<%= course %>"><%= course %></option>
              <% end %>
            </select>
          </div>
          <div class="form-group full horse-fields">
            <input name="race_time" class="clear-field" placeholder="Race Time" />
          </div>
          <div class="checkbox-group mar-top-5">
            <label class="result-checkbox">
              <input type="checkbox" name="won" checked />
              <span><i class="fa fa-smile-o" aria-hidden="true"></i> Won</span>
            </label>
            <label class="result-checkbox">
              <input type="checkbox" name="placed" />
              <span><i class="fa fa-meh-o" aria-hidden="true"></i> Placed</span>
            </label>
            <label class="result-checkbox">
              <input type="checkbox" name="lost" />
              <span><i class="fa fa-frown-o" aria-hidden="true"></i> Lost</span>
            </label>
            <label class="result-checkbox">
              <input type="checkbox" name="void" />
              <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Void</span>
            </label>
          </div>
          <div class="form-actions">
            <a href="#" class="btn btn-primary add-another">Add Another</a>
            <a href="#" class="btn btn-primary save-leg">Done</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/accas/edit.html.erb
<div class="page-title">
  <h1>Edit Acca</h1>
</div>

<%= render "form" %>

app/views/accas/get_acca.js.erb
$('#modal_data').html('<%= escape_javascript(render :partial => "acca") %>');

app/views/accas/import.html.erb
<div class="page-title">
  <h1>Import Acca</h1>
</div>

<div class="flex-row">
  <div class="width-60">
    <div class="form-group html-input">
      <textarea id="acca_html"></textarea>
      <a href="#" class="btn btn-primary btn-full mar-top-10" id="import_acca">Import Acca</a>
    </div>
  </div>

  <div class="width-40">
    <div class="width-100" style="padding:0 0 0 10px;">
      <div id="acca" class="width-100"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $("body").on("click","#import_acca",function(event) {
      event.preventDefault();
      var acca_html = $("#acca_html").val();
      $.ajax({
        url: "/accas/import_acca",
        type: "POST",
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: { "acca_html": acca_html },
        dataType: "script",
        format: "js",
      }).success(function() {
        $("#acca_html").val("");
      });
    });
  });
</script>

app/views/accas/import_acca.js.erb
$('#acca').html('<%= escape_javascript(render :partial => "imported_acca") %>');

app/views/accas/index.html.erb
<div class="page-title">
  <div class="pull-right">
    <%= link_to "Import Accas", import_accas_path, class: "btn btn-primary mobile-hide" %>
  </div>
  <h1>Acca's</h1>
</div>

<%= render "accas" %>

<div class="modal-overlay" style="display:none;">
  <div class="modal">
    <div class="modal-body">
      <div id="modal_data"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $("body").on("click",".get-acca",function(event) {
      event.preventDefault();
      var acca_id = $(this).data("acca-id");
      $.ajax({
        url: "/accas/get_acca",
        type: "GET",
        data: { "id": acca_id },
        dataType: "script",
        format: "js",
      }).success(function() {

      });
    });
  });
</script>

app/views/accas/new.html.erb
<div class="page-title">
  <h1>New Acca</h1>
</div>

<%= render "form" %>